import { normalizeType } from "./categoryMap.js";
import { PcPartPickerInputError } from "./errors.js";

// Lines that are structurally part of PCPartPicker's "Copy/Paste Part List"
// output but are never a component, so they're dropped before per-line
// parsing runs. Matched against the trimmed line, case-insensitively.
const IGNORED_LINE_PATTERNS = [
    /^pcpartpicker part list/i, // header line, with or without the list URL
    /pcpartpicker\.com/i, // catches the URL if it ever appears on its own line
    /^total\s*:/i, // "Total: $496.67"
    /^prices include/i, // "Prices include shipping, taxes, and discounts when available"
    /^generated by/i, // "Generated by PCPartPicker 2026-09-23 01:28 EDT-0400"
    /^compatibility/i, // PCPartPicker's optional "Compatibility: ..." notes line
];

// Matches a trailing "($123.45 @ Retailer)" or "($123.45)" at the very end
// of a line. Only matches when the parenthetical actually opens with a
// dollar amount, so a product name that legitimately ends in parentheses
// (e.g. "Lian Li O11 Dynamic EVO (White)") is left alone.
const PRICE_TAIL_PATTERN =
    /\(\s*\$\s*([\d,]+(?:\.\d+)?)\s*(?:@\s*([^()]+?)\s*)?\)\s*$/;

// Matches a leading "2x " / "2 x " / "2× " quantity marker. Anchored to the
// very start of the (price-stripped) name so it can't misfire on a number
// that appears mid-name — e.g. a RAM kit written as "(2 x 16 GB)" never
// starts at position 0, so it's left alone.
const LEADING_QTY_PATTERN = /^(\d+)\s*[x×]\s+(?=\S)/i;

function shouldIgnoreLine(line) {
    return IGNORED_LINE_PATTERNS.some((pattern) => pattern.test(line));
}

/**
 * Parses a single non-ignored line into a component, or returns null if the
 * line doesn't match the "Type: Name (...)" shape at all (unrecognized
 * text is skipped rather than throwing, so one odd line can't crash the
 * whole import).
 */
function parseLine(line) {
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1) {
        return null;
    }

    const rawType = line.slice(0, colonIndex).trim();
    let rest = line.slice(colonIndex + 1).trim();

    if (!rawType || !rest) {
        return null;
    }

    let sourcePrice = null;
    let sourceRetailer = null;

    const priceMatch = rest.match(PRICE_TAIL_PATTERN);
    if (priceMatch) {
        const numeric = Number.parseFloat(priceMatch[1].replace(/,/g, ""));
        sourcePrice = Number.isFinite(numeric) ? numeric : null;
        sourceRetailer = priceMatch[2] ? priceMatch[2].trim() : null;
        rest = rest.slice(0, priceMatch.index).trim();
    }

    let quantity = 1;
    const qtyMatch = rest.match(LEADING_QTY_PATTERN);
    if (qtyMatch) {
        const parsedQty = Number.parseInt(qtyMatch[1], 10);
        if (Number.isFinite(parsedQty) && parsedQty > 0) {
            quantity = parsedQty;
            rest = rest.slice(qtyMatch[0].length).trim();
        }
    }

    if (!rest) {
        return null;
    }

    return {
        type: normalizeType(rawType),
        name: rest,
        quantity,
        sourcePrice,
        sourceRetailer,
    };
}

/**
 * Parses text copied from PCPartPicker's "Copy/Paste Part List" feature
 * into RigSmith's normalized component shape.
 *
 * This function performs no network access of any kind — it only processes
 * the string it's given. Unrecognized lines are skipped rather than
 * throwing, so malformed or unexpected input degrades gracefully; the
 * function only throws if there's nothing usable at all.
 *
 * @param {string} rawText - the pasted PCPartPicker part list text
 * @returns {{
 *   source: "pcpartpicker",
 *   components: Array<{
 *     type: string,
 *     name: string,
 *     quantity: number,
 *     sourcePrice: number|null,
 *     sourceRetailer: string|null,
 *   }>,
 * }}
 * @throws {PcPartPickerInputError} if the input is empty, or contains no recognizable component lines
 */
export function parsePcPartPickerText(rawText) {
    if (typeof rawText !== "string" || !rawText.trim()) {
        throw new PcPartPickerInputError(
            "Pasted PCPartPicker part list text is required."
        );
    }

    const lines = rawText.split(/\r?\n/);
    const components = [];

    for (const rawLine of lines) {
        const line = rawLine.trim();

        if (!line || shouldIgnoreLine(line)) {
            continue;
        }

        const parsed = parseLine(line);
        if (parsed) {
            components.push(parsed);
        }
    }

    if (components.length === 0) {
        throw new PcPartPickerInputError(
            'No recognizable components were found in the pasted text. Make sure you pasted PCPartPicker\'s "Copy/Paste Part List" output.'
        );
    }

    return {
        source: "pcpartpicker",
        components,
    };
}