import { test, describe } from "node:test";
import assert from "node:assert/strict";

import { parsePcPartPickerText } from "../../services/pcpartpicker/textParser.js";
import { PcPartPickerInputError } from "../../services/pcpartpicker/errors.js";

const SAMPLE_LIST = `PCPartPicker Part List: https://pcpartpicker.com/list/4CQMFP

CPU: AMD Ryzen 7 7800X3D 4.2 GHz 8-Core Processor  ($366.49 @ Amazon)
CPU Cooler: ARCTIC Liquid Freezer III Pro A-RGB 360 77 CFM Liquid CPU Cooler  ($80.19 @ Amazon)
Headphones: HP HyperX Cloud II 7.1 Channel Headset  ($49.99 @ Amazon)
Total: $496.67
Prices include shipping, taxes, and discounts when available
Generated by PCPartPicker 2026-09-23 01:28 EDT-0400`;

describe("parsePcPartPickerText", () => {
    test("parses the documented sample into the expected shape", () => {
        const result = parsePcPartPickerText(SAMPLE_LIST);

        assert.equal(result.source, "pcpartpicker");
        assert.equal(result.components.length, 3);

        assert.deepEqual(result.components[0], {
            type: "CPU",
            name: "AMD Ryzen 7 7800X3D 4.2 GHz 8-Core Processor",
            quantity: 1,
            sourcePrice: 366.49,
            sourceRetailer: "Amazon",
        });
    });

    test("preserves an unsupported category instead of dropping or renaming it", () => {
        const result = parsePcPartPickerText(SAMPLE_LIST);
        const headphones = result.components.find((c) => c.name.includes("HyperX"));

        assert.ok(headphones);
        assert.equal(headphones.type, "Headphones");
    });

    test("ignores the header/URL line, Total line, and footer lines", () => {
        const result = parsePcPartPickerText(SAMPLE_LIST);

        assert.ok(!result.components.some((c) => c.name.includes("pcpartpicker.com")));
        assert.ok(!result.components.some((c) => c.type.toLowerCase() === "total"));
        assert.ok(!result.components.some((c) => c.name.includes("Generated by")));
    });

    test("normalizes known synonyms (Memory -> RAM, Video Card -> GPU, Case Fan -> Case Fans)", () => {
        const text = [
            "Memory: G.Skill Trident Z5 Neo 32 GB (2 x 16 GB) DDR5-6000 CL30  ($129.99 @ B&H)",
            "Video Card: Asus TUF Gaming OC GeForce RTX 4080 SUPER 16 GB  ($999.99 @ Newegg)",
            "Case Fan: Noctua NF-A12x25 PWM 55.5 CFM 120 mm Fan  ($32.95 @ Newegg)",
        ].join("\n");

        const result = parsePcPartPickerText(text);
        const types = result.components.map((c) => c.type);

        assert.deepEqual(types, ["RAM", "GPU", "Case Fans"]);
    });

    test("does not mistake a RAM kit's '2 x 16 GB' for a row quantity", () => {
        const text =
            "Memory: G.Skill Trident Z5 Neo 32 GB (2 x 16 GB) DDR5-6000 CL30  ($129.99 @ B&H)";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].quantity, 1);
        assert.equal(
            result.components[0].name,
            "G.Skill Trident Z5 Neo 32 GB (2 x 16 GB) DDR5-6000 CL30"
        );
    });

    test("extracts a leading '2x ' quantity marker", () => {
        const text = "Case Fans: 2x Noctua NF-A12x25 PWM 55.5 CFM 120 mm Fan  ($65.90 @ Amazon)";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].quantity, 2);
        assert.equal(result.components[0].name, "Noctua NF-A12x25 PWM 55.5 CFM 120 mm Fan");
    });

    test("handles a component with no price/retailer gracefully", () => {
        const text = "Case: Fractal Design North ATX Mid Tower Case";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].sourcePrice, null);
        assert.equal(result.components[0].sourceRetailer, null);
    });

    test("handles a price with no retailer", () => {
        const text = "Case: Fractal Design North ATX Mid Tower Case  ($139.99)";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].sourcePrice, 139.99);
        assert.equal(result.components[0].sourceRetailer, null);
    });

    test("handles a price with a thousands separator", () => {
        const text = "GPU: NVIDIA GeForce RTX 4090  ($1,599.00 @ Newegg)";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].sourcePrice, 1599.0);
    });

    test("does not treat a name ending in non-price parentheses as a price", () => {
        const text = "Case: Lian Li O11 Dynamic EVO (White)";
        const result = parsePcPartPickerText(text);

        assert.equal(result.components[0].name, "Lian Li O11 Dynamic EVO (White)");
        assert.equal(result.components[0].sourcePrice, null);
    });

    test("skips unrecognizable junk lines without crashing", () => {
        const text = [
            "CPU: AMD Ryzen 7 7800X3D  ($366.49 @ Amazon)",
            "some random line with no colon at all",
            "Compatibility: \u2713 No compatibility issues found",
        ].join("\n");

        const result = parsePcPartPickerText(text);
        assert.equal(result.components.length, 1);
        assert.ok(!result.components.some((c) => c.name.includes("random line")));
    });

    test("throws PcPartPickerInputError on empty input", () => {
        assert.throws(() => parsePcPartPickerText(""), PcPartPickerInputError);
        assert.throws(() => parsePcPartPickerText("   "), PcPartPickerInputError);
        assert.throws(() => parsePcPartPickerText(undefined), PcPartPickerInputError);
    });

    test("throws PcPartPickerInputError when nothing recognizable is found", () => {
        const text = [
            "Total: $0.00",
            "Prices include shipping, taxes, and discounts when available",
            "Generated by PCPartPicker 2026-09-23 01:28 EDT-0400",
        ].join("\n");

        assert.throws(() => parsePcPartPickerText(text), PcPartPickerInputError);
    });
});